version: '3.8'

services:
  orchestrator:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - ./p2c.env:/app/p2c.env
      - ./:/app
      - /app/orchestrator/ui/dist
    environment:
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_USERNAME=${MSSQL_USERNAME}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - PROXY_LIST_URLS=https://cdn.jsdelivr.net/gh/proxifly/free-proxy-list@main/proxies/protocols/http/data.txt
    platform: linux/amd64
